typography_spectrum: 0.6268231179565191
color:
  brandColors:
    - '#e6e9ee'
    - '#dca47f'
    - '#6592b3'
    - '#a6c5d9'
    - '#bd8264'
  brandStrength: 0.75
  lightness: 0.40773647697642446
  saturation: 0.5433523328974843
  rhythmicContrast: 0.7166294399648905
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9913
analytics:
  google: null
  facebook: null
  twitter: null
name: Clouds2Words
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
